[build]
builder = "NIXPACKS"

[deploy]
#startCommand = "python agent_runner.py"
startCommand = "python clear_posts.py"
# صيغة Cron (UTC): هذا المثال = 6:00 صباحاً بتوقيت الإمارات (UTC+4) يومياً
cronSchedule = "0 2 * * *"
restartPolicyType = "NEVER"
